#!/bin/bash

#############################################################################################
# Realizar un shell-script que reciba como argumentos números comprendidos entre 1 y 75.
# Dará error en caso de que algún argumento no esté dentro del rango y terminará sin hacer
# nada. En caso contrario generará una línea por cada argumeto con tantos asteriscos como
# indique su argumento.
#############################################################################################
