#!/bin/bash

###########################################################################################
# Un script que convierta a minúsculas los nombres de archivos de un directorio dado por
# teclado.
###########################################################################################

